services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: storage_system
      POSTGRES_USER: storage
      POSTGRES_PASSWORD: storage
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
