// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Demo;

{ITE} {DFMFileType} {AsyncProgressDlg.dfm}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {DFMFileType} {MfClassicDlg.dfm}
{ITE} {DFMFileType} {MfClassicKeysDlg.dfm}
{ITE} {DFMFileType} {MfPlusKeysDlg.dfm}
{ITE} {DFMFileType} {MfPlusSL3Dlg.dfm}
{ITE} {DFMFileType} {MfReaderDlg.dfm}
{ITE} {DFMFileType} {MfReaderMcKeysDlg.dfm}
{ITE} {DFMFileType} {MfReaderMpKeysDlg.dfm}
{ITE} {DFMFileType} {MfSecurityLevelDlg.dfm}
{ITE} {DFMFileType} {MfUltralightDlg.dfm}
{ITE} {DFMFileType} {ProgressDlg.dfm}
{ITE} {DFMFileType} {ReaderDlg.dfm}
{ITE} {DFMFileType} {TemicDlg.dfm}
{ITE} {DFMFileType} {TemicPasswordsDlg.dfm}
{ITE} {DFMFileType} {TmcReaderDlg.dfm}
{ITE} {RCFileType} {Win32\Debug\Demo_DRC.rc}

{$R 'AsyncProgressDlg.dfm' fmAsyncProgressDlg:TForm}
{$R 'Main.dfm' fmMain:TForm}
{$R 'MfClassicDlg.dfm' fmMfClassicDlg:TForm}
{$R 'MfClassicKeysDlg.dfm' fmMfClassicKeysDlg:TForm}
{$R 'MfPlusKeysDlg.dfm' fmMfPlusKeysDlg:TForm}
{$R 'MfPlusSL3Dlg.dfm' fmMfPlusSL3Dlg:TForm}
{$R 'MfReaderDlg.dfm' fmMfReaderDlg:TForm}
{$R 'MfReaderMcKeysDlg.dfm' fmMfReaderMcKeysDlg:TForm}
{$R 'MfReaderMpKeysDlg.dfm' fmMfReaderMpKeysDlg:TForm}
{$R 'MfSecurityLevelDlg.dfm' fmMfSecurityLevelDlg:TForm}
{$R 'MfUltralightDlg.dfm' fmMfUltralightDlg:TForm}
{$R 'ProgressDlg.dfm' fmProgressDlg:TForm}
{$R 'ReaderDlg.dfm' fmReaderDlg:TForm}
{$R 'TemicDlg.dfm' fmTemicDlg:TForm}
{$R 'TemicPasswordsDlg.dfm' fmTemicPasswordsDlg:TForm}
{$R 'TmcReaderDlg.dfm' fmTmcReaderDlg:TForm}
{$R 'Win32\Debug\Demo_DRC.res' 'Win32\Debug\Demo_DRC.rc'}

{$E RUS}

begin
end.
